/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ridwan
 */
public class JualanBuahSaja extends javax.swing.JFrame {

    /**
     * Creates new form JualanBuahSaja
     */
    DefaultTableModel model;
    String namaBuah, jumlahBuah, rd, kb, jenisPembayaran, unitPengukuran;
    
    public JualanBuahSaja() {
        initComponents();
        
        Object kolom[] = {"Nama Buah", "Jumlah Buah", "Harga Buah", "Kondisi Buah", "Jenis Pembayaran", "Total Harga", "Satuan"};
        Object data[][] = {{"Pisang", "123", "Per Kg", "Sudah Matang", "Cash", "Rp 100000", "Ons"}};
        model = new DefaultTableModel(data, kolom);
        
        tblHasil.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJumlahBuah = new javax.swing.JTextField();
        rdKg = new javax.swing.JRadioButton();
        rdEceran = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbJenisPembayaran = new javax.swing.JComboBox<>();
        rdBelum = new javax.swing.JRadioButton();
        rdSudah = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        cmbNamaBuah = new javax.swing.JTextField();
        rdTer = new javax.swing.JRadioButton();
        rdBel = new javax.swing.JRadioButton();
        cmbUnitPengukuran = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nama Buah");

        jLabel2.setText("Jumlah Buah");

        jLabel3.setText("Pembelian");

        jLabel5.setText("Jenis Pembayaran");

        jLabel6.setText("Kondisi Buah");

        buttonGroup1.add(rdKg);
        rdKg.setText("Grosir");
        rdKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKgActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdEceran);
        rdEceran.setText("Eceran");

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel4.setText("BUAH SEGAR SHOP");

        cmbJenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Qris", "Bank" }));

        buttonGroup2.add(rdBelum);
        rdBelum.setText("Setengah Matang");

        buttonGroup2.add(rdSudah);
        rdSudah.setText("Sudah Matang");

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Buah", "Jumlah Buah", "Pembelian", "Kondisi Buah", "Jenis Pembayaran", "Total Harga", "Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHasil.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblHasil);
        tblHasil.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnTambah.setBackground(new java.awt.Color(102, 255, 102));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 102, 102));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 102, 102));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdTer);
        rdTer.setText("Terlalu Matang");

        buttonGroup2.add(rdBel);
        rdBel.setText("Belum Matang");

        cmbUnitPengukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ons", "Gram", "Kg" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdBel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdBelum)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdSudah)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdTer))
                                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJumlahBuah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUnitPengukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNamaBuah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdKg)
                                .addGap(66, 66, 66)
                                .addComponent(rdEceran))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cmbNamaBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJumlahBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnitPengukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdKg)
                    .addComponent(rdEceran))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdBelum)
                    .addComponent(rdSudah)
                    .addComponent(rdTer)
                    .addComponent(rdBel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = tblHasil.getSelectedRow();
        model.removeRow(index);
        tblHasil.setModel(model);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        namaBuah = cmbNamaBuah.getText();
        jumlahBuah = txtJumlahBuah.getText();
        jenisPembayaran = cmbJenisPembayaran.getSelectedItem().toString();
        unitPengukuran = cmbUnitPengukuran.getSelectedItem().toString();

        int jumlah; 
        try {
            jumlah = Integer.parseInt(jumlahBuah);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah Buah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double hargaTotal = 0;

                if (unitPengukuran.equals("Kg")) {
            if (rdKg.isSelected()) {
                rd = "Grosir";
                // Untuk Grosir, minimal pembelian adalah 10 Kg
                if (jumlah < 10) {
                    JOptionPane.showMessageDialog(this, "Minimal pembelian untuk Grosir (Kg) adalah 10 Kg!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                hargaTotal = jumlah * 5000; // Harga untuk Grosir per Kg
            } else {
                JOptionPane.showMessageDialog(this, "Grosir hanya bisa dipilih untuk pembelian per Kg!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (unitPengukuran.equals("Gram")) {
            rd = "Eceran"; // Eceran berlaku untuk Gram
            hargaTotal = jumlah * 3000; // Harga per Gram per 1 Buah
        } else if (unitPengukuran.equals("Ons")) {
            rd = "Eceran"; // Eceran berlaku untuk Ons
            hargaTotal = jumlah * 1000; // Harga per Ons per 1 Buah
        }

        if (rdBelum.isSelected()) {
            kb = "Setengah Matang";
        } else if (rdSudah.isSelected()) {
            kb = "Sudah Matang";
        } else if (rdBel.isSelected()) {
            kb = "Belum Matang";
        } else if (rdTer.isSelected()) {
            kb = "Terlalu Matang";
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menambahkan data berikut?\n" +
            "Nama Buah: " + namaBuah + "\n" +
            "Jumlah Buah: " + jumlah + "\n" +
            "Jenis: " + rd + "\n" +
            "Kondisi: " + kb + "\n" +
            "Jenis Pembayaran: " + jenisPembayaran + "\n" +
            "Total Harga: Rp" + hargaTotal,
            "Konfirmasi Tambah Data", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            model.addRow(new Object[]{namaBuah, jumlah, rd, kb, jenisPembayaran, "Rp " + hargaTotal, unitPengukuran});
            tblHasil.setModel(model);
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak jadi ditambahkan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void rdKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdKgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JualanBuahSaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JualanBuahSaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JualanBuahSaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JualanBuahSaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JualanBuahSaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbJenisPembayaran;
    private javax.swing.JTextField cmbNamaBuah;
    private javax.swing.JComboBox<String> cmbUnitPengukuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdBel;
    private javax.swing.JRadioButton rdBelum;
    private javax.swing.JRadioButton rdEceran;
    private javax.swing.JRadioButton rdKg;
    private javax.swing.JRadioButton rdSudah;
    private javax.swing.JRadioButton rdTer;
    private javax.swing.JTable tblHasil;
    private javax.swing.JTextField txtJumlahBuah;
    // End of variables declaration//GEN-END:variables
}
